Proof of work
lucca65/ex_coin pull request #1
Opened 2017-11-12 14:59 UTC by esdrasedu

2017-11-12 16:33 UTC, lucca65 requested changes
animal! só arruma os nomes das funções pra seguir o snake case!

2017-11-12 17:13 UTC, esdrasedu commented
@lucca65 feito

2017-11-15 19:58 UTC, lucca65 approved these changes

2017-11-15 19:58 UTC, lucca65 commented
@esdrasedu está com erro de compilação

2017-11-16 10:39 UTC, esdrasedu commented
@lucca65 fixed

2017-11-16 14:46 UTC, merged